FROM ubuntu:14.04
RUN apt-get -y update && apt-get -y install wget apache2
# this line of code below is the WRONG way to start the apache2 service.
# RUN service apache2 start
RUN apt-get install -y mysql-server php5 php5-mysql phpmyadmin

# this line of code below is also the WRONG way to start the service.
# CMD /etc/init.d/apache2 start

# Using http://stackoverflow.com/a/27769732/682912
CMD /bin/bash -c "source /etc/apache2/envvars && exec /usr/sbin/apache2 -DFOREGROUND"
