#!/bin/bash
set -e

# same machine name as in Vagrantfile
MACHINE_NAME="vagrant-docker-machine"

# if vm already running, do nothing, only recreate docker-machine
if [[ ! $(vagrant status $MACHINE_NAME) =~ "running" ]]; then
    vagrant up $MACHINE_NAME
fi

# a way to get vagrant vm ip
# http://stackoverflow.com/a/22333221/682912

# NOTE: eth1 interface ip is being retrieved. check
# whether this works in your case.
VAGRANT_IP=$(vagrant ssh -c "ip -o -4 addr show eth1 | sed -e 's/^.*inet //' -e 's/\/.*$//'" | tr -d '\r')
echo "machine ip: $VAGRANT_IP"

# vagrant's autogenerated key path
# http://stackoverflow.com/a/31833042/682912
AUTOGENERATED_KEY_PATH=`pwd`/.vagrant/machines/$MACHINE_NAME/virtualbox/private_key

if [[ ! -f $AUTOGENERATED_KEY_PATH ]]; then
    echo "$AUTOGENERATED_KEY_PATH not found" && exit 1
fi

set -x
docker-machine rm -f $MACHINE_NAME
docker-machine create -d generic \
               --generic-ssh-user vagrant \
               --generic-ssh-key $AUTOGENERATED_KEY_PATH \
               --generic-ip-address $VAGRANT_IP \
               --engine-install-url "https://get.docker.com" \
                $MACHINE_NAME
set +x
