Vagrant.configure("2") do |config|
    
  config.vm.provider :virtualbox do |v|
    v.name = "vagrant-docker-machine"
  end

  # ubuntu box
  config.vm.box = "lattice/ubuntu-trusty-64"

  # boot2docker box
  #config.vm.box = "mitchellh/boot2docker"
  #config.vm.box_url = "https://github.com/mitchellh/boot2docker-vagrant-box/releases/download/v1.2.0/boot2docker_virtualbox.box"
  
  config.vm.provision :docker do |d|
  end
end
